development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: baku_development
  pool: 5
  username: postgres
  password: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: baku_test
  pool: 5
  username: postgres
  password: postgres

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: baku_development
  pool: 5
  username: postgres
  password: postgres
